static const int numThreads = 8;

RWStructuredBuffer<float4> points;
int3 numPoints;
float3 boundsSize;
float3 centre;
float3 offset;
float3 spacing;

int indexFromCoord(uint x, uint y, uint z) 
{
    return z * numPoints.y * numPoints.x + y * numPoints.x + x;
}

float3 posFromCoord(uint x, uint y, uint z)
{
    float3 pos = float3(x * spacing.x, y * spacing.y, z * spacing.z);

    return pos + centre + offset - boundsSize/2;
}